name: Build Penguin Subtitle Player

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'

      - name: Configure with CMake
        run: |
          cmake -S . -B build -G "NMake Makefiles"

      - name: Build project
        run: |
          cmake --build build

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: penguin-exe
          path: build/Penguin-Subtitle-Player.exe
