name: Build Penguin Subtitle Player

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'

      - name: Setup MSVC and build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd %GITHUB_WORKSPACE%
          qmake PenguinSubtitlePlayer.pro
          nmake

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Penguin-Subtitle-Player.exe
          path: release/Penguin-Subtitle-Player.exe
